</sys/doc/fonts

ps:V:	ccc.ps

pdf:V:	ccc.pdf

all:V: pdf ps
	
view:	ps
	page -R ccc.ps

clean:
	rm ccc.ps
	rm ccc.pdf

%.ps:D:	%.ms
	mac=(-ms)
	if(~ $stem comp utf 9 contents) mac=(-ms -mnihongo)
	{ echo $FONTS; cat $stem.ms } | pic | tbl | eqn | 
		troff $mac | lp -dstdout > $target
	/sys/doc/cleanps $target

%.pdf:D: %.ps
	ps2pdf $stem.ps $target
